CREATE TABLE IF NOT EXISTS demo_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    deleted SMALLINT DEFAULT 0
);

INSERT INTO demo_user (name, create_time, update_time, deleted)
SELECT 'Alice', NOW(), NOW(), 0
WHERE NOT EXISTS (SELECT 1 FROM demo_user WHERE name = 'Alice');
