spring:
  application:
    name: demo-order-service
  config:
    import:
      - optional:file:./kset-demo/env/component-mysql.yml
      - optional:file:./kset-demo/env/component-redis.yml
      - optional:file:./kset-demo/env/component-nacos.yml
      - optional:file:./kset-demo/env/component-knife4j.yml

server:
  port: 8082
